version: "3.6"

services:
  redis:
    image: redis/redis-stack-server:7.2.0-v6
    ports:
      - 6969:6379
    environment:
      - REDIS_ARGS=--requirepass password --masterauth password
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "password", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data

volumes:
  redis_data:
